# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.cache/wt [current_project]
set_property parent.project_path /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/ds_top.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/freq_sel.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/freq_sel_wrapper.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/mux.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/mux2_1.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/rc_tp_dac.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/saw_wave.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/sqw_wave.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/tmp_sine.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/tri_wave.v
  /home/ukallakuri/hardware_design/designs/_N4DDA7-DS/_N4DDA7-DS.srcs/sources_1/new/ds_top_wrapper.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ukallakuri/hardware_design/designs/xdcs/timing.xdc
set_property used_in_implementation false [get_files /home/ukallakuri/hardware_design/designs/xdcs/timing.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ds_top_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ds_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ds_top_wrapper_utilization_synth.rpt -pb ds_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
